### ISSUE TITLE
gradioライブラリがエラーを出す

### ISSUE THREAD

**Issue by autumnmotor** [ddPn08/rvc-webui#1]
実行環境: Windows 11, Python 3.9.13, touch 2.1.0.dev20230412+cu118
で、webui-user.batを実行すると以下のようなエラーが出ます。

(venv) PS C:\Users\melan\Documents\GitHub\rvc-webui> ./webui-user.bat
venv "C:\Users\melan\Documents\GitHub\rvc-webui\venv\Scripts\Python.exe"
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Commit hash: 7df7737bc34ff9d3056b4483ee68112ed095d76c
Installing requirements
2023-04-14 06:53:50 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-04-14 06:53:50 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-04-14 06:53:50 | INFO | faiss.loader | Loading faiss.
2023-04-14 06:53:50 | INFO | faiss.loader | Successfully loaded faiss.
gin_channels: 256 self.spk_embed_dim: 109
Traceback (most recent call last):
  File "C:\Users\melan\Documents\GitHub\rvc-webui\webui.py", line 15, in <module>
    webui()
  File "C:\Users\melan\Documents\GitHub\rvc-webui\webui.py", line 5, in webui
    app = ui.create_ui()
  File "C:\Users\melan\Documents\GitHub\rvc-webui\modules\ui.py", line 62, in create_ui
    tab.tab()
  File "C:\Users\melan\Documents\GitHub\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
  File "C:\Users\melan\Documents\GitHub\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 1262, in get_config_file
    "output": list(block.output_api_info()),  # type: ignore
AttributeError: 'Dropdown' object has no attribute 'output_api_info'
続行するには何かキーを押してください . . .

禁じ手ではありますが、gradioライブラリの該当エラーがでている箇所(\lib\site-packages\gradio\blocks.py", line 1261,line 1262,)をコメントアウトしたらwebuiが立ち上がりました。

**Comment by TylorShine** [comment]
こちらの環境では再現したことがありませんが、最新版ではリファクタリングが進んでおり、違う実装になっているため違う動作をするかもしれません。
なお、現最新版 https://github.com/ddPn08/rvc-webui/commit/193d6e718b6be8a6d8efd3346ba7ebe5378ee399 は指定したデータセットの一部しか利用されない不具合があります。 #16 でこれを修正したPRを出しているので取り込まれるまで待ってください。

問題なければこのissueはcloseしていただけますか？

**Comment by autumnmotor** [comment]
返信いただきありがとうございます。
分かりました、後ほど最新版を試してみます。
closeするまで少々お待ちください。

**Comment by autumnmotor** [comment]
今し方、[6f2d7a9](https://github.com/ddPn08/rvc-webui/commit/6f2d7a9a55c839d83c4aca0e278149bcf0bce350)にて、問題なく立ち上がることを確認いたしました。ありがとうございました。
