### ISSUE TITLE
ValueError: too many values to unpack (expected 9)

### ISSUE THREAD

**Issue by Arthur-McArthur** [ddPn08/rvc-webui#17]
Running the webui.bat and I get this output: 

venv "C:\AI\rvc-webui\rvc-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: a4ee6b5c9435f9f9eb4aac786ea23641ee8ff520
Installing requirements
2023-04-23 20:07:06 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-04-23 20:07:06 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-04-23 20:07:06 | INFO | faiss.loader | Loading faiss.
2023-04-23 20:07:06 | INFO | faiss.loader | Successfully loaded faiss.
C:\AI\rvc-webui\rvc-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Number, please remove them: {'step': 1}
  warnings.warn(
Traceback (most recent call last):
  File "C:\AI\rvc-webui\rvc-webui\webui.py", line 15, in <module>
    webui()
  File "C:\AI\rvc-webui\rvc-webui\webui.py", line 5, in webui
    app = ui.create_ui()
  File "C:\AI\rvc-webui\rvc-webui\modules\ui.py", line 133, in create_ui
    tab()
  File "C:\AI\rvc-webui\rvc-webui\modules\ui.py", line 65, in __call__
    return self.ui(outlet)
  File "C:\AI\rvc-webui\rvc-webui\modules\tabs\merge.py", line 277, in ui
    (
ValueError: too many values to unpack (expected 9)
Press any key to continue . . .

**Comment by ddPn08** [comment]
Probably fixed.

**Comment by Arthur-McArthur** [comment]
Working now, thanks for the quick fix!!
