### ISSUE TITLE
webui-user.batを実行中にエラーが発生しました。

### ISSUE THREAD

**Issue by sonic191514935245** [ddPn08/rvc-webui#18]
実行環境: Windows 11, Python 3.11.3
でwebui-user.batを実行すると、以下のようなエラーが発生しました。
venv "C:\tails.exe\rvc-webui\venv\Scripts\Python.exe"
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
Commit hash: a9572ebc20d5cbe6a0c7d998a14d9530a51b7a0c
Traceback (most recent call last):
  File "C:\tails.exe\rvc-webui\launch.py", line 164, in <module>
    prepare_environment()
  File "C:\tails.exe\rvc-webui\launch.py", line 136, in prepare_environment
    run_python(
  File "C:\tails.exe\rvc-webui\launch.py", line 84, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tails.exe\rvc-webui\launch.py", line 36, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "C:\tails.exe\rvc-webui\venv\Scripts\Python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
Assertion Error: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

続行するには何かキーを押してください . . . 

この場合、どの箇所を修正すればよろしいでしょうか？
よろしければ詳しい手順も教えていただけますと幸いです。
何卒よろしくお願いいたします。
![RVC-WebUI Error](https://user-images.githubusercontent.com/124413913/233885062-c0c34301-5cf3-4f62-a681-8a70f3455ee9.png)

**Comment by ddPn08** [comment]
これはGPUが正しく認識されていない時に起こるエラーですね。
使用しているPCのグラフィックボードの種類を教えてください。

**Comment by sonic191514935245** [comment]
ご返信ありがとうございます。
Intel(R) UHD Graphics 600だと思います。
もし間違っていたら、PCのどの画面から確認できるか教えていただけますと幸いです。
お手数をおかけしてすみません。
何卒よろしくお願いいたします。

**Comment by ddPn08** [comment]
82047f7026dae6663874f93436bd0a4d793071df
こちらのコミットで修正されました。ご確認ください。

**Comment by sonic191514935245** [comment]
誠にありがとうございます！これから確認させていただきます。
この修正を自分のPC内のファイルに適用するためには、再度このページをgit cloneすればよろしいでしょうか？
修正されたことが確認でき次第、このissueはcloseさせていただきます。
本当にありがとうございました！

**Comment by ddPn08** [comment]
フォルダの中にある`update.bat`を実行することによって自動で更新されるかと思います！

**Comment by sonic191514935245** [comment]
ありがとうございます！ただいま確認中です。
issueのcloseについては、少々お待ちいただけますと幸いです。
また何かありましたら連絡させていただきます。

**Comment by sonic191514935245** [comment]
![スクリーンショット (3)](https://user-images.githubusercontent.com/124413913/234161812-37bdc582-63db-4a15-b990-2bbf5893b76a.png)
![スクリーンショット (4)](https://user-images.githubusercontent.com/124413913/234161817-3eb1d965-d9d9-4ea4-8808-a8f59d540298.png)
![スクリーンショット (11)](https://user-images.githubusercontent.com/124413913/234161820-19e198e9-9281-4e42-ad26-4edecb16dde5.png)
![スクリーンショット (16)](https://user-images.githubusercontent.com/124413913/234161824-bd51c7b4-bb32-48f8-98b3-be4e22f4a15e.png)
![スクリーンショット (17)](https://user-images.githubusercontent.com/124413913/234161825-8cbe62c8-b0c8-4d8f-96d7-3bc1c3db0fd9.png)
申し訳ございません。
次は添付画像のようなエラーが発生しました。
RuntimeError: Cannot install on Python version 3.11.3; only versions >=3.7,<3.11 are supported.
との事ですが、バージョン3.11までのPythonを再インストールすればよろしいでしょうか？
また、notice欄のpipのアップデート方法についても教えていただけますと幸いです。
再びお手数をおかけしてしまい、大変申し訳ございません。
何卒よろしくお願いいたします。

**Comment by ddPn08** [comment]
サポートされているpythonのバージョンは3.10までですね、なので3.10をインストールして再度試していただけると助かります！

**Comment by sonic191514935245** [comment]
ありがとうございます！これから再試行してみます。

**Comment by sonic191514935245** [comment]
申し訳ございません。
バージョン3.10.11のPythonをインストールして再試行したのですが、添付画像のようなエラーが発生しました。
RuntimeError: Couldn't install torch.
との事ですが、torchというものをインストールして再試行すればよろしいでしょうか？
また、notice欄のpipのアップデートは行わなくても問題ないのでしょうか？
再びお手数をおかけしてしまい、大変申し訳ございません。
何卒よろしくお願いいたします。
![スクリーンショット (18)](https://user-images.githubusercontent.com/124413913/234169804-3e1939dd-d28a-431c-91d6-ced5fe156cc8.png)
![スクリーンショット (19)](https://user-images.githubusercontent.com/124413913/234169812-be48b677-8cc3-42d6-b4a4-31b90d00ab87.png)
![スクリーンショット (20)](https://user-images.githubusercontent.com/124413913/234169815-ba3ce656-c154-4f3b-abeb-afefe463ff84.png)

**Comment by ddPn08** [comment]
これはメモリが足りない時に起こるエラーのようです。お使いのPCのメモリ容量はどれくらいですか？

**Comment by sonic191514935245** [comment]
RAMのことでよろしいでしょうか？
12.0GBの内11.8GB使用可能です。

**Comment by ddPn08** [comment]
少し面倒になるのですが。
rvc-webuiのフォルダ内でコマンドプロンプトを開いていただいて、
```
.\venv\Scripts\activate.bat
pip install torch torchvision torchaudio --no-cache-dir
pip install -r requirements.txt --no-cache-dir
```
を実行してみてください。

**Comment by sonic191514935245** [comment]
ありがとうございます！早速試してみます。

**Comment by sonic191514935245** [comment]
![スクリーンショット (21)](https://user-images.githubusercontent.com/124413913/234466568-f8576a36-be6f-4389-b613-ab4c4683a596.png)
![スクリーンショット (22)](https://user-images.githubusercontent.com/124413913/234466579-fc4c0a2f-de82-48a4-9527-856f1be73e6f.png)
![スクリーンショット (23)](https://user-images.githubusercontent.com/124413913/234466582-3bee2141-f63f-4de3-a2c3-a7cac7198f50.png)
申し訳ございません。
次は画像のようなエラーが発生しました。
黄色の文字の警告は対処しなくても大丈夫だと思うのですが、Microsoft Visual C++ 14.0以降をインストールして再試行すればよろしいでしょうか？
何度もお手数をおかけしてしまい、本当に申し訳ございません。
何卒よろしくお願いいたします。

**Comment by ddPn08** [comment]
おっしゃる通りC++ Build Toolsが必要になります。
こちらをご参照ください。
https://github.com/ddPn08/rvc-webui#troubleshooting

**Comment by sonic191514935245** [comment]
ありがとうございます！
ただいまMicrosoft Visual C++ 14.0をインストールしており、終了し次第改めて確認させていただきます。
その時に問題がなければ、このissueはこのままcloseさせていただきたいと思います。
何度もお手数をおかけしてしまい、大変申し訳ございませんでした。
改めまして、この度は親切に対応していただき本当にありがとうございました！

**Comment by sonic191514935245** [comment]
![スクリーンショット (25)](https://user-images.githubusercontent.com/124413913/234762298-f4a29bd0-2cfe-47d8-80f4-19014216e50e.png)
![スクリーンショット (26)](https://user-images.githubusercontent.com/124413913/234762315-623493da-474c-456d-83aa-cf87385f8b23.png)
![スクリーンショット (27)](https://user-images.githubusercontent.com/124413913/234762320-2735d0b6-4f58-46fe-8cda-a837771e99c1.png)
![スクリーンショット (28)](https://user-images.githubusercontent.com/124413913/234762326-72eba8fa-c438-4297-bb3a-b111b0ba52c9.png)
![スクリーンショット (29)](https://user-images.githubusercontent.com/124413913/234762331-15048e5a-ae03-4510-b5f9-22b5b5452bee.png)
![スクリーンショット (30)](https://user-images.githubusercontent.com/124413913/234762336-2a5b6a09-71f4-43e8-84d7-44af86d032a7.png)
申し訳ございません。
Microsoft Visual C++ 14.0をインストール後、
.\venv\Scripts\activate.bat
pip install torch torchvision torchaudio --no-cache-dir
pip install -r requirements.txt --no-cache-dir
を実行してから再度webui-user.batを実行したのですが、次は画像のようなエラーが発生しました。
stderr: ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\kenya\\AppData\\Local\\Temp\\pip-build-tracker-g54ptg7o\\b3759f218065381a7fd40f76aceb0a3d9a194994167753c35c1de2ee
との事ですが、ファイルを削除した覚えはありません。
この場合、どの箇所を修正すればよろしいでしょうか？
よろしければ詳しい手順も教えていただけますと幸いです。
再びお手数をおかけしてしまい、大変申し訳ございません。
何卒よろしくお願いいたします。

**Comment by sonic191514935245** [comment]
![スクリーンショット (31)](https://user-images.githubusercontent.com/124413913/234777192-cf60ea7f-3e4f-49a6-ba77-ae0241065df5.png)
pipをアップデートしてから再度webui-user.batを実行してみたのですが、次は画像のようなエラーが発生しました。
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
との事ですが、NVIDIA製のGPUがない場合はRVC WebUIは使用できないということでしょうか？
何度もお手数をおかけしてしまい、本当に申し訳ございません。
何卒よろしくお願いいたします。

**Comment by ddPn08** [comment]
こちらの実装ミスでした！先ほど修正いたしましたので再度ご確認ください。

**Comment by sonic191514935245** [comment]
ありがとうございます！早速確認させていただきます。

**Comment by sonic191514935245** [comment]
![スクリーンショット (32)](https://user-images.githubusercontent.com/124413913/235048338-9718048c-09de-4d39-8f61-5442a28dd24f.png)
これで一応インストールは完了したと思うのですが、
Warning: You have unused kwarg parameters in Checkbox, please remove them: {'disabled': True}
  warnings.warn(
というメッセージがあり、使用しなかったkwargパラメーターというのをremoveする方法が分かりません。
この場合、どの箇所を修正すればよろしいでしょうか？
よろしければ詳しい手順も教えていただけますと幸いです。
何卒よろしくお願いいたします。

**Comment by ddPn08** [comment]
それはWarningですので無視していただいて大丈夫です！

**Comment by sonic191514935245** [comment]
ありがとうございます！
おかげさまで、先ほど無事にサイトを開くことができました。
正常に動作することが確認でき次第、このissueはcloseさせていただきたいと思います。
コマンドプロンプト等はほとんど触ったことがなく、全くの初心者でしたが、ddPn08さんのおかげで無事に実用化することができました。
何度もお手数をおかけしてしまい、大変申し訳ございませんでした。
改めまして、この度は親切に対応していただき本当にありがとうございました！

**Comment by sonic191514935245** [comment]
![スクリーンショット (34)](https://user-images.githubusercontent.com/124413913/235828005-c0600e32-0d75-43d4-9b66-5de574b4b8ac.png)
![スクリーンショット (35)](https://user-images.githubusercontent.com/124413913/235828012-e7a6403b-d35c-4c58-8d42-07812e5125db.png)
![スクリーンショット (36)](https://user-images.githubusercontent.com/124413913/235828014-70d7eea1-0778-4467-95fb-33d70da08590.png)
![スクリーンショット (37)](https://user-images.githubusercontent.com/124413913/235828017-6d99dbe4-7c42-44a2-af47-24fdf60a61b7.png)
![スクリーンショット (38)](https://user-images.githubusercontent.com/124413913/235828020-0e776eb9-e66d-4d4b-b1c3-7b48614bbdd9.png)
申し訳ございません。
学習を始めることには成功したのですが、Model trainingが中々進まず、一日以上待機していたところ、次は画像のようなエラーが発生しました。
RuntimeError: Parent directory C:\tails.exe\rvc-webui\models\training\models\ずんだもん\state does not exist.
との事ですが、該当するフォルダーは生成されており、中身だけがない状態でした。
この場合、学習時の設定に問題があったのでしょうか？
または、やはりNVIDIA製のGPUでなければ実用は厳しい等、こちらのPCのスペックの問題でしょうか？
再びお手数をおかけしてしまい、大変申し訳ございません。
何卒よろしくお願いいたします。

**Comment by ddPn08** [comment]
いえCPUでもしっかり動作していると思います！
おそらくパスに日本語が入っているのがよくないのかもしれません
こちらでも調べてみます！

**Comment by sonic191514935245** [comment]
ありがとうございます！こちらの方でも再試行してみます。

**Comment by sonic191514935245** [comment]
お久しぶりです。
新しいノートパソコンを購入して再度インストールしたのですが、学習を始めたところ画像のようなエラーが発生しており、Preprocessingから進みませんでした。
実行環境:Windows 11, Python 3.10.11
GPUは2つあり、片方はIntel(R) Iris(R) Xe Graphics, もう片方はNVIDIA GeForce RTX 3060 Laptop GPUなのですが、GPUを複数使用するように設定する方法がわからなかったのでGPU IDは0にしました。
学習時の設定の画像も添付いたします。
![スクリーンショット (1)](https://github.com/ddPn08/rvc-webui/assets/124413913/8b7fbb63-fd4f-4f70-a090-0ac694d5953d)
![スクリーンショット (2)](https://github.com/ddPn08/rvc-webui/assets/124413913/24db5f8a-c73c-4ed3-9330-2d3107a88e8a)
![スクリーンショット (3)](https://github.com/ddPn08/rvc-webui/assets/124413913/3b6fb6d8-2823-47e9-9f01-38306ea5f7be)
![スクリーンショット (4)](https://github.com/ddPn08/rvc-webui/assets/124413913/d20f7ce0-1b73-47f1-bad7-51a93df00dde)
![スクリーンショット (5)](https://github.com/ddPn08/rvc-webui/assets/124413913/789409a9-23a3-4b2e-8225-9334ec27acf6)
![スクリーンショット (6)](https://github.com/ddPn08/rvc-webui/assets/124413913/8b0a3da1-0678-4441-bdee-f13a46958bf3)
![スクリーンショット (7)](https://github.com/ddPn08/rvc-webui/assets/124413913/7d47bbc6-d1c2-4fec-af12-35b551b317c9)
![スクリーンショット (8)](https://github.com/ddPn08/rvc-webui/assets/124413913/dc0a1623-db63-46d6-b487-f675d065cab2)
![スクリーンショット (9)](https://github.com/ddPn08/rvc-webui/assets/124413913/98c7ba95-9716-4e1a-8146-60d7bff82683)
![スクリーンショット (10)](https://github.com/ddPn08/rvc-webui/assets/124413913/870b5724-2047-41f0-b047-bd3c3d0b081a)
![スクリーンショット (11)](https://github.com/ddPn08/rvc-webui/assets/124413913/f8284bec-f1ff-4f82-af52-584c5c50dfec)
![スクリーンショット (12)](https://github.com/ddPn08/rvc-webui/assets/124413913/e883786b-7737-4b16-ae03-9f9694d88b37)
![スクリーンショット (14)](https://github.com/ddPn08/rvc-webui/assets/124413913/205e2378-595d-42a5-aaa2-0dcd2c024009)

ImportError: Unable to import ...
numpy: DLL load failed while importing ...: ページングファイルが小さすぎるため、この操作を完了できません。
等様々なエラーが発生しており、申し訳ないのですが私では何をどうすればよいのかわからず、手が付けられない状況です。
8枚目の画像には
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
とありますが、NumPyとは何か、またNumPyのバージョンを確認する方法がリンク先のサイトを確認してもわかりませんでした。
この場合、どの箇所を修正すればよろしいでしょうか？
また、よろしければGPUを複数使うように設定する方法も教えていただけますと幸いです。
非常にお忙しい中何度もお手数をおかけしてしまい、大変申し訳ございませんが、ここまで来たらぜひ実用化したいので、何卒よろしくお願いいたします。

**Comment by sonic191514935245** [comment]
![スクリーンショット (15)](https://github.com/ddPn08/rvc-webui/assets/124413913/83be2c3f-d667-4177-a2ad-e0f620695f53)
![スクリーンショット (16)](https://github.com/ddPn08/rvc-webui/assets/124413913/70c7898e-ae4d-4058-a346-6062c34527ce)
![スクリーンショット (17)](https://github.com/ddPn08/rvc-webui/assets/124413913/89df3bcd-4928-4566-b375-a030bd77e1fc)
GPU IDを0,1にして再試行したところ、次は画像のようなエラーが発生しました。
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
とのことですが、CUDAとは何か、またCUDAに対して何をどうすればよいのかわからず、手が付けられない状況です。
この場合、どの箇所を修正すればよろしいでしょうか？
また、よろしければGPUを複数使うように設定する方法も教えていただけますと幸いです。
非常にお忙しい中何度もお手数をおかけしてしまい、大変申し訳ございません。
ただ、プロフィール(?)を拝見したところ非常にお忙しいようなので、ぜひお時間のある時にご返信いただけますと幸いです。
何卒よろしくお願いいたします。
