### ISSUE TITLE
how to download models?

### ISSUE THREAD

**Issue by lioriky6** [ddPn08/rvc-webui#25]
I have downloaded the webui and I downloaded a zip file that contains 2 .pth files and 1 json and I don't understand how do I add the model to the webui, I tried to put the file in the checkpoints folder but nothing happens, even after I reload page or press on the recycle button.
What am I missing?

**Comment by JoaCHIP** [comment]
Apart from the 4 built-in files (guanguan, keruan, kiki, youzhan), a lot of the files i've tried putting into the "weights" folder causes a python error when selecting the file in the drop-down. Example:

```2024-01-09 19:44:54 | INFO | infer.modules.vc.modules | Loading: assets/weights/hubert_base.pth
Traceback (most recent call last):
  File "D:\Programs\RVC1006Nvidia\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\Programs\RVC1006Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "D:\Programs\RVC1006Nvidia\runtime\lib\site-packages\gradio\blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Programs\RVC1006Nvidia\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Programs\RVC1006Nvidia\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Programs\RVC1006Nvidia\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Programs\RVC1006Nvidia\infer\modules\vc\modules.py", line 102, in get_vc
    self.tgt_sr = self.cpt["config"][-1]
KeyError: 'config'
```

Edit: I've found out that .pth files can be many different things. They are not necessarily compatible with this. Maybe some sort of naming convention is needed to help people who are new to all this.
