### ISSUE TITLE
モデル学習時のエラー

### ISSUE THREAD

**Issue by xmeta** [ddPn08/rvc-webui#26]
## 実行環境
* OS: Windows 11
* RAM: 32GB
* CPU: AMD Ryzen 7 3700X 8-Core
* GPU: RTX 2070 SUPER

## 発生した事象
モデルの学習を行おうとすると、下記のエラーが表示され学習が行われない。

## エラーログ
````
E:\rvc-webui-main\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Checkbox, please remove them: {'disabled': False}
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:07 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss.
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:07 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss.
2023-05-02 17:33:07 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-02 17:33:07 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:07 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss.
2023-05-02 17:33:07 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:07 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss.
2023-05-02 17:33:07 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:07 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss.
2023-05-02 17:33:07 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:07 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss.
2023-05-02 17:33:07 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:07 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss.
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:07 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:07 | INFO | faiss.loader | Loading faiss.
2023-05-02 17:33:08 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-02 17:33:08 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-02 17:33:08 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:08 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:08 | INFO | faiss.loader | Loading faiss.
2023-05-02 17:33:08 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:08 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:08 | INFO | faiss.loader | Loading faiss.
2023-05-02 17:33:08 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-02 17:33:08 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:08 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:08 | INFO | faiss.loader | Loading faiss.
2023-05-02 17:33:08 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:08 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:08 | INFO | faiss.loader | Loading faiss.
2023-05-02 17:33:09 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:09 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:09 | INFO | faiss.loader | Loading faiss.
2023-05-02 17:33:09 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:09 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:09 | INFO | faiss.loader | Loading faiss.
2023-05-02 17:33:09 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:09 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:09 | INFO | faiss.loader | Loading faiss.
2023-05-02 17:33:09 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-02 17:33:09 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-02 17:33:09 | INFO | faiss.loader | Loading faiss.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\rvc-webui-main\webui.py", line 3, in <module>
    from modules import cmd_opts, ui
  File "E:\rvc-webui-main\modules\ui.py", line 9, in <module>
    from . import models, shared
  File "E:\rvc-webui-main\modules\models.py", line 13, in <module>
    from lib.rvc.pipeline import VocalConvertPipeline
  File "E:\rvc-webui-main\lib\rvc\pipeline.py", line 9, in <module>
    import scipy.signal as signal
  File "E:\rvc-webui-main\venv\lib\site-packages\scipy\signal\__init__.py", line 323, in <module>
    from ._filter_design import *
  File "E:\rvc-webui-main\venv\lib\site-packages\scipy\signal\_filter_design.py", line 16, in <module>
    from scipy import special, optimize, fft as sp_fft
  File "E:\rvc-webui-main\venv\lib\site-packages\scipy\__init__.py", line 225, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\rvc-webui-main\venv\lib\site-packages\scipy\optimize\__init__.py", line 421, in <module>
    from ._shgo import shgo
  File "E:\rvc-webui-main\venv\lib\site-packages\scipy\optimize\_shgo.py", line 9, in <module>
    from scipy import spatial
  File "E:\rvc-webui-main\venv\lib\site-packages\scipy\__init__.py", line 225, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\rvc-webui-main\venv\lib\site-packages\scipy\spatial\__init__.py", line 107, in <module>
    from ._qhull import *
ImportError: DLL load failed while importing _qhull: ページング ファイルが小さすぎるため、この操作を完了できません。
````

**Comment by ddPn08** [comment]
前処理に使うCPUこプロセス数が多すぎるのかと思われます。
`Number of CPU processes`を減らしてお試しください。

**Comment by xmeta** [comment]
16から8に減らしたところ無事処理が開始されました、ありがとうございます。

[Retrieval-based-Voice-Conversion-WebUI](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI)ですと、論理コア数と同じ16でいけたのでそのまま同じ設定をしておりました。
