### ISSUE TITLE
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory

### ISSUE THREAD

**Issue by mossly** [ddPn08/rvc-webui#29]
Webui.bat and webui-user.bat are throwing this error:

`venv "D:\audiogen\rvc-webui-main\venv\Scripts\Python.exe"
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
Commit hash: <none>
Installing requirements
Traceback (most recent call last):
  File "D:\audiogen\rvc-webui-main\webui.py", line 3, in <module>
    from modules import cmd_opts, ui
  File "D:\audiogen\rvc-webui-main\modules\ui.py", line 9, in <module>
    from . import models, shared
  File "D:\audiogen\rvc-webui-main\modules\models.py", line 6, in <module>
    from fairseq import checkpoint_utils
  File "D:\audiogen\rvc-webui-main\venv\Lib\site-packages\fairseq\__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "D:\audiogen\rvc-webui-main\venv\Lib\site-packages\fairseq\distributed\__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "D:\audiogen\rvc-webui-main\venv\Lib\site-packages\fairseq\distributed\fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "D:\audiogen\rvc-webui-main\venv\Lib\site-packages\fairseq\dataclass\__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "D:\audiogen\rvc-webui-main\venv\Lib\site-packages\fairseq\dataclass\configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Python311\Lib\dataclasses.py", line 1221, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Python311\Lib\dataclasses.py", line 1211, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\dataclasses.py", line 959, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\dataclasses.py", line 816, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
Press any key to continue . . .`

**Comment by ddPn08** [comment]
python 3.11 is not supported. Sorry to trouble you, but please try python3.10.

**Comment by mossly** [comment]
Thanks for pointing this out to me! Cheers

**Comment by IMHFX** [comment]
> 不支持 Python 3.11。很抱歉给您带来麻烦，但请尝试 python3.10。

3.10依然报错
