### ISSUE TITLE
トレーニング再開でエラー

### ISSUE THREAD

**Issue by hetima** [ddPn08/rvc-webui#3]
途中経過ファイルが存在する状態でトレーニング再開すると以下のエラーが出ます。

```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "G:\venv\RVC\.venv\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "G:\venv\RVC\rvc-webui\modules\training\train.py", line 506, in run
    lr=float(lr),
UnboundLocalError: local variable 'lr' referenced before assignment
```

**Comment by ddPn08** [comment]
先ほど修正いたしました！ご確認ください
https://github.com/ddPn08/rvc-webui/commit/cf4416e10249e88ca0184a001f36a81872e72e8e

**Comment by hetima** [comment]
動作しました。ありがとうございます
