### ISSUE TITLE
トレーニングでエラーが出る

### ISSUE THREAD

**Issue by sugarkwork** [ddPn08/rvc-webui#33]
トレーニングを処理開始すると以下のエラーがでます。

train_all: emb_name: contentvec█████████████████████████████████████████████████▉  | 1008/1036 [00:28<00:00, 46.31it/s]
Traceback (most recent call last):████████████████████████████████████████████████▊| 1033/1036 [00:28<00:00, 55.81it/s]
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\ai\rvc-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\ai\rvc-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\ai\rvc-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "F:\ai\rvc-webui\modules\tabs\training.py", line 183, in train_all
    train_model(
  File "F:\ai\rvc-webui\lib\rvc\train.py", line 199, in train_model
    if device.type == "mps":
AttributeError: 'NoneType' object has no attribute 'type'

設定は以下の通りです。

Ignore cache 有効
Speaker ID : 0
Target sampling rate: 40k
f0 Model: Yes
Using phone embedder: contentvec
Embedding channels: 256
GPU ID: 0, 1
Number of CPU processes: 8
Normalize audio volume when preprocess: Yes
Pitch extraction algorithm: harvest
Batch size: 14
Number of epochs: 50
Save every epoch: 10
Cache batch: On
FP16: On
Pre trained generator path: F:\ai\rvc-webui\models\pretrained\f0G40k256.pth
Pre trained discriminator path: F:\ai\rvc-webui\models\pretrained\f0D40k256.pth

パラメータ（Using phone embedder とか Target sampling rate とか）を少しずつ変えて試しましたが、改善しませんでした。
グラボは2枚乗せています。

どのようにすればよいでしょうか。

**Comment by ddPn08** [comment]
705e9aa6bdccc85be05926bd3e80fc4e62005ee7 で修正しました。ご確認ください

**Comment by sugarkwork** [comment]
対応ありがとうございます。
試しましたが改善していないようです

train_all: emb_name: contentvec
Traceback (most recent call last):
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\ai\rvc-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\ai\rvc-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\ai\rvc-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "F:\ai\rvc-webui\modules\tabs\training.py", line 183, in train_all
    train_model(
  File "F:\ai\rvc-webui\lib\rvc\train.py", line 199, in train_model
    if device.type == "mps":
AttributeError: 'NoneType' object has no attribute 'type'
train_all: emb_name: hubert-base-japanese
Traceback (most recent call last):
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\ai\rvc-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\ai\rvc-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\ai\rvc-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "F:\ai\rvc-webui\modules\tabs\training.py", line 183, in train_all
    train_model(
  File "F:\ai\rvc-webui\lib\rvc\train.py", line 199, in train_model
    if device.type == "mps":
AttributeError: 'NoneType' object has no attribute 'type'

GPUID を　0　だけにすれば完了しました

GPUIDを　１　だけにすると別なエラーが出ました

100%|███████████████████████████████████████████████████████████████████████████| 2072/2072 [00:00<00:00, 27992.47it/s]
GPU 1 is not available                                                                        | 0/2072 [00:00<?, ?it/s]
Traceback (most recent call last):██████████████████████████████████████████████████▋| 258/259 [01:19<00:00,  5.41it/s]
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\routes.py", line 412, in run_predict/259 [01:19<00:00,  4.63it/s]
    output = await app.get_blocks().process_api(████████████████████████████████████▋| 258/259 [01:19<00:00,  5.94it/s]
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api259 [01:20<00:00,  5.90it/s]
    result = await self.call_function(███████████████████████████████████████████████| 259/259 [01:20<00:00,  5.36it/s]
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 1035, in call_function9 [01:14<00:03,  3.28it/s]
    prediction = await anyio.to_thread.run_sync(
  File "F:\ai\rvc-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\ai\rvc-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\ai\rvc-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\ai\rvc-webui\venv\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "F:\ai\rvc-webui\modules\tabs\training.py", line 172, in train_all
    create_dataset_meta(training_dir, sampling_rate_str, f0)
  File "F:\ai\rvc-webui\lib\rvc\train.py", line 91, in create_dataset_meta
    names = set(list_data(gt_wavs_dir)) & set(list_data(co256_dir))
  File "F:\ai\rvc-webui\lib\rvc\train.py", line 85, in list_data
    for subdir in os.listdir(dir):
  File "F:\ai\rvc-webui\webui.py", line 10, in listdir4mac
    return [file for file in _list_dir(path) if not file.startswith(".")]
FileNotFoundError: [WinError 3] 指定されたパスが見つかりません。: 'F:\\ai\\rvc-webui\\models\\training\\models\\test05\\3_feature256'

**Comment by ddPn08** [comment]
再度修正しました！ご確認ください

**Comment by sugarkwork** [comment]
ありがとうございます。動作しました！
素早い対応ありがとうございます。

**Comment by leospark** [comment]
@ddPn08 thanks for your job. I am trying to train my own model with multi-gpus. I have repaired some problems mentioned above. But I got a new error as the following:
`    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/lipingping/software/anaconda3/envs/afcc/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
    while not context.join():
  File "/home/lipingping/software/anaconda3/envs/afcc/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/lipingping/software/anaconda3/envs/afcc/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/home/lipingping/project/afcc/modules/../lib/rvc/train.py", line 605, in training_runner
    net_g.module.load_state_dict(net_g_state)
  File "/home/lipingping/software/anaconda3/envs/afcc/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SynthesizerTrnMs256NSFSid' object has no attribute 'module'
`
![image](https://github.com/ddPn08/rvc-webui/assets/34911790/324498b9-2c7f-409a-b83d-498a107d5955)

I will appreciate it for any advice. Looking forward to the reply.
