### ISSUE TITLE
webui-user.bat　でエラーが起こる。

### ISSUE THREAD

**Issue by tai-calg** [ddPn08/rvc-webui#36]
webui-user.batを実行した際以下のようなエラーが発生しました。
依存しているライブラリによるエラーのように見えるのですが、どのようにすればよろしいでしょうか。
状態としてはupdate.batを行った後です。
よろしくお願いいたします。

```
venv "C:\User\......\rvc-webui-main\venv\Scripts\Python.exe"
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
Commit hash: c7aa393122803193f93e89a0739db415413f6340
Installing requirements
Traceback (most recent call last):
  File "C:\User\......\rvc-webui-main\webui.py", line 3, in <module>
    from modules import cmd_opts, ui
  File "C:\User\......\rvc-webui-main\modules\ui.py", line 9, in <module>
    from . import models, shared
  File "C:\User\......\rvc-webui-main\modules\models.py", line 6, in <module>
    from fairseq import checkpoint_utils
  File "C:\User\......\rvc-webui-main\venv\Lib\site-packages\fairseq\__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "C:\User\......\rvc-webui-main\venv\Lib\site-packages\fairseq\distributed\__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "C:\User\......\rvc-webui-main\venv\Lib\site-packages\fairseq\distributed\fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "C:\User\......\rvc-webui-main\venv\Lib\site-packages\fairseq\dataclass\__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "C:\User\......\rvc-webui-main\venv\Lib\site-packages\fairseq\dataclass\configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Python311\Lib\dataclasses.py", line 1223, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Python311\Lib\dataclasses.py", line 1213, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
```

**Comment by ddPn08** [comment]
python3.11はサポートしておりません；
お手数ですが、python3.10を使用して再度お試しください。
