### ISSUE TITLE
training中に指定されたパスが見つかりませんとエラーが出る。

### ISSUE THREAD

**Issue by kei527** [ddPn08/rvc-webui#39]
タイトルの通りですがtrainingの準備段階でエラーが発生します。
動作環境は
windows11
python 3.10.9
4070ti＋13700Fです

ファイル名に2バイト文字を入れない、c直下に置く等考えられる対策は行いましたが改善しなかったため
投稿させていただきます。

以下コマンドプロンプトです

```
To create a public link, set `share=True` in `launch()`.
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-17 22:11:45 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss.
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-17 22:11:45 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss.
2023-05-17 22:11:45 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-17 22:11:45 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss.
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-17 22:11:45 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss.
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-17 22:11:45 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss.
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-17 22:11:45 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss.
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-17 22:11:45 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-17 22:11:45 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss.
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss.
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-17 22:11:45 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss.
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-17 22:11:45 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss.
2023-05-17 22:11:45 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-17 22:11:45 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss.
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-17 22:11:45 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-17 22:11:45 | INFO | faiss.loader | Loading faiss.
2023-05-17 22:11:46 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-17 22:11:46 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-17 22:11:47 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-17 22:11:47 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-17 22:11:47 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-17 22:11:47 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-17 22:11:47 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-17 22:11:47 | INFO | faiss.loader | Successfully loaded faiss.
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
2023-05-17 22:11:48 | INFO | faiss.loader | Successfully loaded faiss.
2023-05-17 22:11:49 | INFO | faiss.loader | Successfully loaded faiss.
Traceback (most recent call last):
  File "C:\rvc-webui\venv\lib\site-packages\gradio\routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\rvc-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\rvc-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\rvc-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\rvc-webui\venv\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "C:\rvc-webui\modules\tabs\training.py", line 68, in train_index_only
    extract_f0.run(training_dir, num_cpu_process, pitch_extraction_algo)
  File "C:\rvc-webui\lib\rvc\preprocessing\extract_f0.py", line 128, in run
    for pathname in sorted(list(os.listdir(dataset_dir))):
  File "C:\rvc-webui\webui.py", line 10, in listdir4mac
    return [file for file in _list_dir(path) if not file.startswith(".")]
FileNotFoundError: [WinError 3] 指定されたパスが見つかりません。: 'C:\\rvc-webui\\models\\training\\models\\test\\1_16k_wavs'
```

**Comment by takemi323** [comment]
私も同じ問題が起きています。
＜動作環境＞
Windows11
Python 3.10.9

昨日、https://ddpn08.fanbox.cc/posts/5709928 の手順に従ってWebUIを起動し、
一度は問題なくTrainすることも、既存の音声ファイルを変換することもできました。
しかし、次に別の名前でTrainしようとすると、

FileNotFoundError: [WinError 3] 指定されたパスが見つかりません。: 〜〜〜

が出て先に進まない状況です。
