### ISSUE TITLE
学習を開始するとRuntimeErrorとなる

### ISSUE THREAD

**Issue by seisein** [ddPn08/rvc-webui#50]
学習を開始すると以下のようにRuntimeErrorとなり、Internal Server Errorとなります。
原因、解消方法などご教授頂きたいと思います。

2023-06-01 22:40:56 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
2023-06-01 22:47:03 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
2023-06-01 22:47:03 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
2023-06-01 22:47:03 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
2023-06-01 22:47:03 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
2023-06-01 22:47:03 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
train_all: emb_name: contentvec
Traceback (most recent call last):
  File "E:\AIVoice\rvc-webui\venv\lib\site-packages\gradio\routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AIVoice\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "E:\AIVoice\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AIVoice\rvc-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AIVoice\rvc-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\AIVoice\rvc-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\AIVoice\rvc-webui\venv\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "E:\AIVoice\rvc-webui\modules\tabs\training.py", line 246, in train_all
    train_model(
  File "E:\AIVoice\rvc-webui\lib\rvc\train.py", line 338, in train_model
    training_runner(
  File "E:\AIVoice\rvc-webui\lib\rvc\train.py", line 446, in training_runner
    dist.init_process_group(
  **File "E:\AIVoice\rvc-webui\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 865, in init_process_group
    raise RuntimeError("trying to initialize the default process group " "twice!")**
RuntimeError: trying to initialize the default process group twice!
**2023-06-01 22:47:03 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 500 Internal Server Error"**
2023-06-01 22:47:03 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"

**Comment by ddPn08** [comment]
duplicate of #46
