### ISSUE TITLE
help with seperating vocals

### ISSUE THREAD

**Issue by titgfggggh** [ddPn08/rvc-webui#57]
this the error i got while i tried to seperate vocals from a song:You Only Live Once - The Strokes - 2023 Cover Version (320 kbps).mp3.reformatted.wav->Traceback (most recent call last):
  File "D:\voice\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "D:\voice\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\soundfile.py", line 655, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "D:\voice\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\soundfile.py", line 1213, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'D:\\voice\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/You Only Live Once - The Strokes - 2023 Cover Version (320 kbps).mp3.reformatted.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\voice\Retrieval-based-Voice-Conversion-WebUI\infer-web.py", line 370, in uvr
    pre_fun._path_audio_(
  File "D:\voice\Retrieval-based-Voice-Conversion-WebUI\infer_uvr5.py", line 64, in _path_audio_
    ) = librosa.core.load(  # 理论上librosa读取可能对某些音频有bug，应该上ffmpeg读取，但是太麻烦了弃坑
  File "D:\voice\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "D:\voice\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "D:\voice\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "D:\voice\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\audioread\__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "D:\voice\Retrieval-based-Voice-Conversion-WebUI\runtime\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\voice\\Retrieval-based-Voice-Conversion-WebUI\\TEMP/You Only Live Once - The Strokes - 2023 Cover Version (320 kbps).mp3.reformatted.wav'
![image](https://github.com/ddPn08/rvc-webui/assets/62062399/082f13c8-3421-4ec2-80bd-f592aed2cd6d)

**Comment by terracottahaniwa** [comment]
Retrieval-based-Voice-Conversion-WebUI and RVC-WebUI are two different projects. you can contact the repository Retrieval-based-Voice-Conversion-WebUI you using.

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues

however, you probably have the wrong path. on windows, the path separator is \ not /.
also, paths containing multibyte characters or spaces can cause problems.
