### ISSUE TITLE
突然Launchができなくなりました

### ISSUE THREAD

**Issue by HimawariDeguchi** [ddPn08/rvc-webui#68]
Python 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]
Commit hash: 3aed3783879637ad4d73ddb7b393857d674c2adc
Installing requirements
Traceback (most recent call last):
  File "/content/rvc-webui/webui.py", line 3, in <module>
    from modules import cmd_opts, ui
  File "/content/rvc-webui/modules/ui.py", line 9, in <module>
    from . import models, shared
  File "/content/rvc-webui/modules/models.py", line 6, in <module>
    from fairseq import checkpoint_utils
  File "/opt/conda/lib/python3.11/site-packages/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/opt/conda/lib/python3.11/site-packages/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/opt/conda/lib/python3.11/site-packages/fairseq/distributed/fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/opt/conda/lib/python3.11/site-packages/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/opt/conda/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory

URLが出力されることなく、出力が終わってしまいます
PC初心者なのでどうすれば良いかわかりやすくご教授いただければ幸いです

**Comment by ddPn08** [comment]
Colabを使用されているようですが、どのノートブックをお使いでしょうか？

**Comment by HimawariDeguchi** [comment]
Google Colabの自分のアカウントのdriveにコピーしたものです

**Comment by HimawariDeguchi** [comment]
こちらのURL上のものを使わせていただいてます
https://github.com/ddPn08/rvc-webui-colab

**Comment by ddPn08** [comment]
先ほどノートブックの方を修正しましたので、再度コピーして試してみてください。

**Comment by HimawariDeguchi** [comment]
できました
ありがとうございます
