### ISSUE TITLE
UnboundLocalError: local variable 'loss_gen_all' referenced before assignment

### ISSUE THREAD

**Issue by OnfireGGs** [ddPn08/rvc-webui#8]
こんなエラーが出ます
Win10,Python 3.10.11, torch2.0.0+cu118

2023-04-18 19:18:49 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-04-18 19:18:49 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-04-18 19:18:49 | INFO | faiss.loader | Loading faiss.
2023-04-18 19:18:50 | INFO | faiss.loader | Successfully loaded faiss.
2023-04-18 19:18:55 | INFO | torch.distributed.distributed_c10d | Added key: store_based_barrier_key:1 to store for rank: 0
2023-04-18 19:18:55 | INFO | torch.distributed.distributed_c10d | Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
gin_channels: 256 self.spk_embed_dim: 109
loaded pretrained C:\rvc\rvc-webui\models\pretrained\f0G40k.pth C:\rvc\rvc-webui\models\pretrained\f0D40k.pth
0it [00:00, ?it/s, epoch=1]
Traceback (most recent call last):
  File "C:\rvc\rvc-webui\venv\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\rvc\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "C:\rvc\rvc-webui\venv\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\rvc\rvc-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\rvc\rvc-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\rvc\rvc-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\rvc\rvc-webui\venv\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "C:\rvc\rvc-webui\modules\tabs\training.py", line 112, in train_all
    train_model(
  File "C:\rvc\rvc-webui\modules\training\train.py", line 182, in train_model
    mp.spawn(
  File "C:\rvc\rvc-webui\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "C:\rvc\rvc-webui\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "C:\rvc\rvc-webui\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\rvc\rvc-webui\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "C:\rvc\rvc-webui\modules\training\train.py", line 623, in training_runner
    loss_g=float(loss_gen_all),
UnboundLocalError: local variable 'loss_gen_all' referenced before assignment

**Comment by ddPn08** [comment]
mainブランチにマージされました
