### ISSUE TITLE
セットアップエラー

### ISSUE THREAD

**Issue by harumaki4649** [ddPn08/rvc-webui#80]
fairseq==0.12.2のインストールでエラーが発生します。

**Comment by harumaki4649** [comment]
Building wheels for collected packages: fairseq
  Building editable for fairseq (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building editable for fairseq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [120 lines of output]
      running editable_wheel
      creating C:\Users\suppo\AppData\Local\Temp\pip-wheel-n8nyecjh\.tmp-3tf0yhi8\fairseq.egg-info
      writing C:\Users\suppo\AppData\Local\Temp\pip-wheel-n8nyecjh\.tmp-3tf0yhi8\fairseq.egg-info\PKG-INFO
      writing dependency_links to C:\Users\suppo\AppData\Local\Temp\pip-wheel-n8nyecjh\.tmp-3tf0yhi8\fairseq.egg-info\dependency_links.txt
      writing entry points to C:\Users\suppo\AppData\Local\Temp\pip-wheel-n8nyecjh\.tmp-3tf0yhi8\fairseq.egg-info\entry_points.txt
      writing requirements to C:\Users\suppo\AppData\Local\Temp\pip-wheel-n8nyecjh\.tmp-3tf0yhi8\fairseq.egg-info\requires.txt
      writing top-level names to C:\Users\suppo\AppData\Local\Temp\pip-wheel-n8nyecjh\.tmp-3tf0yhi8\fairseq.egg-info\top_level.txt
      writing manifest file 'C:\Users\suppo\AppData\Local\Temp\pip-wheel-n8nyecjh\.tmp-3tf0yhi8\fairseq.egg-info\SOURCES.txt'
      reading manifest file 'C:\Users\suppo\AppData\Local\Temp\pip-wheel-n8nyecjh\.tmp-3tf0yhi8\fairseq.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'C:\Users\suppo\AppData\Local\Temp\pip-wheel-n8nyecjh\.tmp-3tf0yhi8\fairseq.egg-info\SOURCES.txt'
      creating 'C:\Users\suppo\AppData\Local\Temp\pip-wheel-n8nyecjh\.tmp-3tf0yhi8\fairseq-0.12.2.dist-info'
      creating C:\Users\suppo\AppData\Local\Temp\pip-wheel-n8nyecjh\.tmp-3tf0yhi8\fairseq-0.12.2.dist-info\WHEEL
      running build_py
      running build_ext
      building 'fairseq.libbleu' extension
      creating C:\Users\suppo\AppData\Local\Temp\tmpas1hn0vd.build-temp\Release
      creating C:\Users\suppo\AppData\Local\Temp\tmpas1hn0vd.build-temp\Release\fairseq
      creating C:\Users\suppo\AppData\Local\Temp\tmpas1hn0vd.build-temp\Release\fairseq\clib
      creating C:\Users\suppo\AppData\Local\Temp\tmpas1hn0vd.build-temp\Release\fairseq\clib\libbleu
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64_x86\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-Ic:\program files\python38\include" "-Ic:\program files\python38\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /EHsc /Tpfairseq/clib/libbleu/libbleu.cpp /FoC:\Users\suppo\AppData\Local\Temp\tmpas1hn0vd.build-temp\Release\fairseq/clib/libbleu/libbleu.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -std=c++11 -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=libbleu -D_GLIBCXX_USE_CXX11_ABI=0
      cl : コマンド ライン warning D9002 : 不明なオプション '-std=c++11' を無視します。
      cl : コマンド ライン warning D9002 : 不明なオプション '-O3' を無視します。
      libbleu.cpp
      fairseq/clib/libbleu/libbleu.cpp(60): warning C4305: '初期化中': 'unsigned __int64' から 'std::size_t' へ切り詰め ます。
      fairseq/clib/libbleu/libbleu.cpp(60): warning C4309: '初期化中': 定数値が切り捨てられました。
      fairseq/clib/libbleu/libbleu.cpp(61): warning C4305: '初期化中': '__int64' から 'std::size_t' へ切り詰めます。
      fairseq/clib/libbleu/libbleu.cpp(61): warning C4309: '初期化中': 定数値が切り捨てられました。
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64_x86\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-Ic:\program files\python38\include" "-Ic:\program files\python38\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /EHsc /Tpfairseq/clib/libbleu/module.cpp /FoC:\Users\suppo\AppData\Local\Temp\tmpas1hn0vd.build-temp\Release\fairseq/clib/libbleu/module.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -std=c++11 -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=libbleu -D_GLIBCXX_USE_CXX11_ABI=0
      cl : コマンド ライン warning D9002 : 不明なオプション '-std=c++11' を無視します。
      cl : コマンド ライン warning D9002 : 不明なオプション '-O3' を無視します。
      module.cpp
      c:\program files\python38\include\pyconfig.h(206): fatal error C1083: include ファイルを開けません。'basetsd.h':No such file or directory
      No CUDA runtime is found, using CUDA_HOME='C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\v11.7'
      C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\wheel\bdist_wheel.py:109: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
        if get_flag("Py_DEBUG", hasattr(sys, "gettotalrefcount"), warn=(impl == "cp")):
      Traceback (most recent call last):
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 419, in compile
          self.spawn(args)
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 734, in spawn
          return original_spawn(cmd)
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 517, in spawn
          return super().spawn(cmd, env=env)
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\_distutils\spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64_x86\\cl.exe' failed with exit code 2

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 156, in run
          self._create_wheel_file(bdist_wheel)
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 345, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 268, in _run_build_commands
          self._run_build_subcommands()
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 295, in _run_build_subcommands
          self.run_command(name)
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\Cython\Distutils\build_ext.py", line 127, in build_extension
          super(build_ext, self).build_extension(ext)
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 738, in win_wrap_single_compile
          return original_compile(sources, output_dir, macros,
        File "C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 421, in compile
          raise CompileError(msg)
      distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64_x86\\cl.exe' failed with exit code 2
      C:\Users\suppo\AppData\Local\Temp\pip-build-env-g_jwl8zh\overlay\Lib\site-packages\setuptools\_distutils\dist.py:988: _DebuggingTips: Problem in editable installation.
      !!

              ********************************************************************************
              An error happened while installing `fairseq` in editable mode.

              The following steps are recommended to help debug this problem:

              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.

              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:

                  https://github.com/pypa/setuptools/issues

              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************

      !!
        cmd_obj.run()
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64_x86\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

**Comment by harumaki4649** [comment]
これがそのエラーの全文です

**Comment by harumaki4649** [comment]
新しいエラーが出ました。
Python38\include" "-IC:\Program Files\Python38\Include" /EHsc /Tpfairseq/clib/libbleu/libbleu.cpp /Fobuild\temp.win-amd64-cpython-38\Release\fairseq/clib/libbleu/libbleu.obj -std=c++11 -O3
  error: command 'cl.exe' failed: None
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

**Comment by harumaki4649** [comment]
追記：最初に提供したエラーは出なくなりました。

**Comment by harumaki4649** [comment]
エラーの抜けていた部分です。
 copying fairseq\config\model\wav2vec2\wav2vec2_large.yaml -> build\lib.win-amd64-cpython-38\fairseq\config\model\wav2vec2
  running build_ext
  building 'fairseq.libbleu' extension
  creating build\temp.win-amd64-cpython-38
  creating build\temp.win-amd64-cpython-38\Release
  creating build\temp.win-amd64-cpython-38\Release\fairseq
  creating build\temp.win-amd64-cpython-38\Release\fairseq\clib
  creating build\temp.win-amd64-cpython-38\Release\fairseq\clib\libbleu
  cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\suppo\Downloads\rvc-webui-main\venv\include "-IC:\Program Files\Python38\include" "-IC:\Program Files\Python38\Include" /EHsc /Tpfairseq/clib/libbleu/libbleu.cpp /Fobuild\temp.win-amd64-cpython-38\Release\fairseq/clib/libbleu/libbleu.obj -std=c++11 -O3
  error: command 'cl.exe' failed: None
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

**Comment by harumaki4649** [comment]
https://www.delftstack.com/ja/howto/python/python-command-cl-exe-failed-no-such-file-or-directory/
に従えば解決可能
